sudo:
  - required

services:
  - docker

script:
  - docker build -t example .
  - docker run --rm example make


deploy:
   provider:
     - releases
   api_key:
       secure: "sXz3J+8MJMg4LOCm1mvOMbWUjUG0xikaL2pY99JuQKguFkQ7YBNlGwk16tWOCPFvO3+u4yYm+vn85yC3JTfVZyDbtcIe1xGzU2GYcfrCL0iUhMcRGPRXeEKv+Js18hWSRNhx1eh4LuFv+gNjG5V/Pg//QEciNdYINAHUGeJPLB7QXx5Ig3nJTMwZ27up4cPGVuLUAstpl/Lm01ciX0/gYSadN0ebgMHkd7OwaM04/ovcOsdrastS5zq3ti7+YBE9L5/F6LqymyB7SqI/FzAz8w6EpJ6qtFPSO7eO/rAddaxWkBIKqOY319wRhpji1j3aQluONW5pF9O2TJSQhPpwn5EhTwsktLgC8bfPzygWruqH5J0CncJ84jD0BTCoO1OWsDhb3i5xsz2VhpuVP6+JgaNIAXjPKfPj/Hqy1/sQjbRBjgazICtSmpFqZitblM/cxFfzplyPkfwDlqEpvcg4O2+rU6gn+GOECljiBeHj9Qu5j53ugBM/EoJOIPGWJwjFpGG1gp910VS+tJAp5WS0u8cdXQ9lfGdWQUIL6WsLh7SGNg6yOIUXdi40bTSxuNHXiYdDCCBHPv9GJ7W1NpmZqrjZrySpCUfDydcehRCFp5GKy8zgoeUzHAuXPa9fd9OzCCRgG6hwDdj/d5g1Wzoe3tpAJL5/T6GDjEwzoQ3sdbw="
   file: 
     - example.pdf
   skip_cleanup: 
     - true
   on:
       tags: false
