sudo:
  - required

services:
  - docker

script:
  # - docker build -t example .
  # - docker run --rm example make
  - echo "test" > example.pdf
  - ls


deploy:
   provider:
     - releases
   api_key:
         secure: "X/jZXgCMdWR6bXac9416YeX7gd3ZYV5mfpdUReOlbBfemhzmB8L+yJh3c9JctX1SM53XMF8NZ/HYTMujhVwEKPZYnNpCpUZhjn/5dsKk+aifzmXSWgNsEp4ItpzFM2iFWyoF3nmF8m9fRQ691CAP/6cUtVwqDibP+PET9CEqpPflPKJ5c/QdvYrCA7Z4V4EPZ/eM19B1cFkvS270JO96tOg8Yi7tnawl7YQp6hSxjH0ZhunwohtHB+VtK3K19AeIuQso5KiSthnMirJf5hR2iqGGhv1f7DY76YDzzepQ4q6CzGItzTJq4BEJMPwFiJr8dsFHcjYaquKAjdx9Pd9yHbI+NZ72FIycW79+8REXSjESN6Ff9v0uI0xSOECuEeVc7Zyk9hHPb3sOpLWOaS3ljRW9enalZLtYZk+kpV0VDzZx4X2QoDt25K8cGPhifgAxVmhgiZy6I+iUqBrfwTvXzCOzkRLKs6VtLWwU2RDBHXTVQzV5xJQUszY5CtIFEVUnA5q9c9vFrsebZoEMwPwVSE7P2Cunqmf7CnqKfIK+KsRls5gsaPCkAA2bQGga7bEQSLvlHxKB0U0Ky2h3377KZrWKRG/wXtTDZ5buTGZqkzoYGOdJ5SL3/Ht5mQBthu9zaLTA63YLOWMLAe+tdxKBnOHYP+Mi5oSLN8uvcfG47Kk="
   file: 
     - example.pdf
   skip_cleanup: 
     - true
   on:
       tags: false
